### ISSUE TITLE
iOS Swift application

### ISSUE THREAD

**Issue by Falsen** [RISE-drones/rise_drones#44]
It is mentioned that there is a Swift application that can be used with this software. Where can that application be found?

**Comment by agising** [comment]
Hello,

Yes, there is s swift application that has not yet been released because it is cumbersome to instruct how to set up everything. I'm looking into releasing it with very limited support as for now.

**Comment by agising** [comment]
It is now released. Please help contributing!
[git@github.com:RISE-drones/DSS-DJI-iOS.git](https://github.com/RISE-drones/DSS-DJI-iOS)

The interface i currently set up for specific application. Hide buttons in ViewDidLoad to quickly clean up.
